#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

#clang -ggdb3 -O0 -std=c11 -Wall -Werror -o fifteen fifteen.c -lcs50 -lm
fifteen: fifteen.c
	gcc -ggdb3 -O0 -std=gnu99 -Wall -Werror -o fifteen -lcs50 fifteen.c -lm

clean:
	rm -f *.o a.out core fifteen
