#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

#clang -ggdb3 -O0 -std=c11 -Wall -Werror -o fifteen fifteen.c -lcs50 -lm
fifteen: fifteen.c
	gcc -std=c11 fifteen.c fifteen

clean:
	rm -f *.o a.out core fifteen
